-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ExternalData/maintenance/abstractSchemaChanges/patch-ed_url_cache-drop-post_vars.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
ALTER TABLE ed_url_cache
  DROP post_vars;
