-- This file is automatically generated using maintenance/generateSchemaChangeSql.php.
-- Source: extensions/ExternalData/maintenance/abstractSchemaChanges/patch-ed_url_cache-drop-post_vars.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TEMPORARY TABLE /*_*/__temp__ed_url_cache AS
SELECT
  id,
  url,
  req_time,
  result
FROM /*_*/ed_url_cache;
DROP TABLE /*_*/ed_url_cache;


CREATE TABLE /*_*/ed_url_cache (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    url BLOB NOT NULL, req_time INTEGER NOT NULL,
    result CLOB NOT NULL
  );
INSERT INTO /*_*/ed_url_cache (id, url, req_time, result)
SELECT
  id,
  url,
  req_time,
  result
FROM
  /*_*/__temp__ed_url_cache;
DROP TABLE /*_*/__temp__ed_url_cache;

CREATE UNIQUE INDEX id ON /*_*/ed_url_cache (id);

CREATE INDEX url ON /*_*/ed_url_cache (url);
